# Generated by Django 5.1.4 on 2025-01-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_status_report_status1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='status1',
            new_name='status',
        ),
    ]
